// Generated by gencpp from file dmp/SetActiveDMPResponse.msg
// DO NOT EDIT!


#ifndef DMP_MESSAGE_SETACTIVEDMPRESPONSE_H
#define DMP_MESSAGE_SETACTIVEDMPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dmp
{
template <class ContainerAllocator>
struct SetActiveDMPResponse_
{
  typedef SetActiveDMPResponse_<ContainerAllocator> Type;

  SetActiveDMPResponse_()
    : success(false)  {
    }
  SetActiveDMPResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::dmp::SetActiveDMPResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dmp::SetActiveDMPResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetActiveDMPResponse_

typedef ::dmp::SetActiveDMPResponse_<std::allocator<void> > SetActiveDMPResponse;

typedef boost::shared_ptr< ::dmp::SetActiveDMPResponse > SetActiveDMPResponsePtr;
typedef boost::shared_ptr< ::dmp::SetActiveDMPResponse const> SetActiveDMPResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dmp::SetActiveDMPResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dmp::SetActiveDMPResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dmp::SetActiveDMPResponse_<ContainerAllocator1> & lhs, const ::dmp::SetActiveDMPResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dmp::SetActiveDMPResponse_<ContainerAllocator1> & lhs, const ::dmp::SetActiveDMPResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dmp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dmp::SetActiveDMPResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dmp::SetActiveDMPResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dmp::SetActiveDMPResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dmp::SetActiveDMPResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dmp::SetActiveDMPResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dmp::SetActiveDMPResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dmp::SetActiveDMPResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::dmp::SetActiveDMPResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::dmp::SetActiveDMPResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dmp/SetActiveDMPResponse";
  }

  static const char* value(const ::dmp::SetActiveDMPResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dmp::SetActiveDMPResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"#True if no errors\n"
"bool success\n"
"\n"
"\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::dmp::SetActiveDMPResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dmp::SetActiveDMPResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetActiveDMPResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dmp::SetActiveDMPResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dmp::SetActiveDMPResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DMP_MESSAGE_SETACTIVEDMPRESPONSE_H
