// Generated by gencpp from file movement_primitives/PrompTrainMsg.msg
// DO NOT EDIT!


#ifndef MOVEMENT_PRIMITIVES_MESSAGE_PROMPTRAINMSG_H
#define MOVEMENT_PRIMITIVES_MESSAGE_PROMPTRAINMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement_primitives
{
template <class ContainerAllocator>
struct PrompTrainMsg_
{
  typedef PrompTrainMsg_<ContainerAllocator> Type;

  PrompTrainMsg_()
    : promp_name()
    , path_to_data()
    , sensor_dofs(0)
    , robot_dofs(0)  {
    }
  PrompTrainMsg_(const ContainerAllocator& _alloc)
    : promp_name(_alloc)
    , path_to_data(_alloc)
    , sensor_dofs(0)
    , robot_dofs(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _promp_name_type;
  _promp_name_type promp_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _path_to_data_type;
  _path_to_data_type path_to_data;

   typedef int8_t _sensor_dofs_type;
  _sensor_dofs_type sensor_dofs;

   typedef int8_t _robot_dofs_type;
  _robot_dofs_type robot_dofs;





  typedef boost::shared_ptr< ::movement_primitives::PrompTrainMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_primitives::PrompTrainMsg_<ContainerAllocator> const> ConstPtr;

}; // struct PrompTrainMsg_

typedef ::movement_primitives::PrompTrainMsg_<std::allocator<void> > PrompTrainMsg;

typedef boost::shared_ptr< ::movement_primitives::PrompTrainMsg > PrompTrainMsgPtr;
typedef boost::shared_ptr< ::movement_primitives::PrompTrainMsg const> PrompTrainMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_primitives::PrompTrainMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_primitives::PrompTrainMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_primitives::PrompTrainMsg_<ContainerAllocator1> & lhs, const ::movement_primitives::PrompTrainMsg_<ContainerAllocator2> & rhs)
{
  return lhs.promp_name == rhs.promp_name &&
    lhs.path_to_data == rhs.path_to_data &&
    lhs.sensor_dofs == rhs.sensor_dofs &&
    lhs.robot_dofs == rhs.robot_dofs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_primitives::PrompTrainMsg_<ContainerAllocator1> & lhs, const ::movement_primitives::PrompTrainMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_primitives

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_primitives::PrompTrainMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_primitives::PrompTrainMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_primitives::PrompTrainMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_primitives::PrompTrainMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_primitives::PrompTrainMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_primitives::PrompTrainMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_primitives::PrompTrainMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4ac2b3de384f10c19d662ca80d3020f8";
  }

  static const char* value(const ::movement_primitives::PrompTrainMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4ac2b3de384f10c1ULL;
  static const uint64_t static_value2 = 0x9d662ca80d3020f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_primitives::PrompTrainMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_primitives/PrompTrainMsg";
  }

  static const char* value(const ::movement_primitives::PrompTrainMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_primitives::PrompTrainMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string promp_name\n"
"string path_to_data\n"
"int8 sensor_dofs #Number of individual numbers in the sensor input\n"
"int8 robot_dofs #Number of controllable robot joints\n"
;
  }

  static const char* value(const ::movement_primitives::PrompTrainMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_primitives::PrompTrainMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.promp_name);
      stream.next(m.path_to_data);
      stream.next(m.sensor_dofs);
      stream.next(m.robot_dofs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PrompTrainMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_primitives::PrompTrainMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_primitives::PrompTrainMsg_<ContainerAllocator>& v)
  {
    s << indent << "promp_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.promp_name);
    s << indent << "path_to_data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.path_to_data);
    s << indent << "sensor_dofs: ";
    Printer<int8_t>::stream(s, indent + "  ", v.sensor_dofs);
    s << indent << "robot_dofs: ";
    Printer<int8_t>::stream(s, indent + "  ", v.robot_dofs);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_PRIMITIVES_MESSAGE_PROMPTRAINMSG_H
