// Generated by gencpp from file movement_primitives/PrompTrainResponse.msg
// DO NOT EDIT!


#ifndef MOVEMENT_PRIMITIVES_MESSAGE_PROMPTRAINRESPONSE_H
#define MOVEMENT_PRIMITIVES_MESSAGE_PROMPTRAINRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/UInt32MultiArray.h>

namespace movement_primitives
{
template <class ContainerAllocator>
struct PrompTrainResponse_
{
  typedef PrompTrainResponse_<ContainerAllocator> Type;

  PrompTrainResponse_()
    : traj_data()  {
    }
  PrompTrainResponse_(const ContainerAllocator& _alloc)
    : traj_data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::UInt32MultiArray_<ContainerAllocator>  _traj_data_type;
  _traj_data_type traj_data;





  typedef boost::shared_ptr< ::movement_primitives::PrompTrainResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_primitives::PrompTrainResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PrompTrainResponse_

typedef ::movement_primitives::PrompTrainResponse_<std::allocator<void> > PrompTrainResponse;

typedef boost::shared_ptr< ::movement_primitives::PrompTrainResponse > PrompTrainResponsePtr;
typedef boost::shared_ptr< ::movement_primitives::PrompTrainResponse const> PrompTrainResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_primitives::PrompTrainResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_primitives::PrompTrainResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_primitives::PrompTrainResponse_<ContainerAllocator1> & lhs, const ::movement_primitives::PrompTrainResponse_<ContainerAllocator2> & rhs)
{
  return lhs.traj_data == rhs.traj_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_primitives::PrompTrainResponse_<ContainerAllocator1> & lhs, const ::movement_primitives::PrompTrainResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_primitives

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_primitives::PrompTrainResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_primitives::PrompTrainResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_primitives::PrompTrainResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_primitives::PrompTrainResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_primitives::PrompTrainResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_primitives::PrompTrainResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_primitives::PrompTrainResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "595c9731a2b15adf7f3b40e8c7419b64";
  }

  static const char* value(const ::movement_primitives::PrompTrainResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x595c9731a2b15adfULL;
  static const uint64_t static_value2 = 0x7f3b40e8c7419b64ULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_primitives::PrompTrainResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_primitives/PrompTrainResponse";
  }

  static const char* value(const ::movement_primitives::PrompTrainResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_primitives::PrompTrainResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#uint32 step\n"
"#uint32[] traj_data\n"
"std_msgs/UInt32MultiArray traj_data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/UInt32MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"uint32[]          data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::movement_primitives::PrompTrainResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_primitives::PrompTrainResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.traj_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PrompTrainResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_primitives::PrompTrainResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_primitives::PrompTrainResponse_<ContainerAllocator>& v)
  {
    s << indent << "traj_data: ";
    s << std::endl;
    Printer< ::std_msgs::UInt32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.traj_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_PRIMITIVES_MESSAGE_PROMPTRAINRESPONSE_H
