// Generated by gencpp from file movement_primitives/PrompTrain.msg
// DO NOT EDIT!


#ifndef MOVEMENT_PRIMITIVES_MESSAGE_PROMPTRAIN_H
#define MOVEMENT_PRIMITIVES_MESSAGE_PROMPTRAIN_H

#include <ros/service_traits.h>


#include <movement_primitives/PrompTrainRequest.h>
#include <movement_primitives/PrompTrainResponse.h>


namespace movement_primitives
{

struct PrompTrain
{

typedef PrompTrainRequest Request;
typedef PrompTrainResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PrompTrain
} // namespace movement_primitives


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement_primitives::PrompTrain > {
  static const char* value()
  {
    return "bae4a804188261b587b4284e77e5b0ba";
  }

  static const char* value(const ::movement_primitives::PrompTrain&) { return value(); }
};

template<>
struct DataType< ::movement_primitives::PrompTrain > {
  static const char* value()
  {
    return "movement_primitives/PrompTrain";
  }

  static const char* value(const ::movement_primitives::PrompTrain&) { return value(); }
};


// service_traits::MD5Sum< ::movement_primitives::PrompTrainRequest> should match
// service_traits::MD5Sum< ::movement_primitives::PrompTrain >
template<>
struct MD5Sum< ::movement_primitives::PrompTrainRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement_primitives::PrompTrain >::value();
  }
  static const char* value(const ::movement_primitives::PrompTrainRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_primitives::PrompTrainRequest> should match
// service_traits::DataType< ::movement_primitives::PrompTrain >
template<>
struct DataType< ::movement_primitives::PrompTrainRequest>
{
  static const char* value()
  {
    return DataType< ::movement_primitives::PrompTrain >::value();
  }
  static const char* value(const ::movement_primitives::PrompTrainRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement_primitives::PrompTrainResponse> should match
// service_traits::MD5Sum< ::movement_primitives::PrompTrain >
template<>
struct MD5Sum< ::movement_primitives::PrompTrainResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement_primitives::PrompTrain >::value();
  }
  static const char* value(const ::movement_primitives::PrompTrainResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_primitives::PrompTrainResponse> should match
// service_traits::DataType< ::movement_primitives::PrompTrain >
template<>
struct DataType< ::movement_primitives::PrompTrainResponse>
{
  static const char* value()
  {
    return DataType< ::movement_primitives::PrompTrain >::value();
  }
  static const char* value(const ::movement_primitives::PrompTrainResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_PRIMITIVES_MESSAGE_PROMPTRAIN_H
